### ISSUE TITLE
Remove Indents

### ISSUE THREAD

**Issue by sqeptyk** [xhuajin/obsidian-tabs#48]
Is there any way to remove the indents for nested tabs and for tab content?

**Comment by xhuajin** [comment]
Setting the contents padding to 0 in Settings allows the text to be left. However, in this case, other text indentation needs to be written in css for example

```css
.tabs-container > .tabs-contents > .tabs-content > :not(.tabs-container) {
  padding: 1em 2em;
}
```
